name: Run HNX Bond Script

on:
  schedule:
    - cron: '0 11 * * *'  # chạy 18h VN
  workflow_dispatch:

jobs:
  run-bond:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install libraries
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python bond_mualai.py
